import { useState } from 'react'
import { PrincipalLayoutProps } from './types'
import Head from 'next/head'
import styles from './PrincipalLayout.module.css'

// fonts
import { Inter } from "next/font/google"
import LateralBar from '../PrincipalLateralBar'
import TopBar from '../PrincipalTopBar'

const inter = Inter({ subsets: ['latin'] })

export default function Layout( props : PrincipalLayoutProps ){

    const [isLoading, setIsLoading] = useState(true);

    return(
        <>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <LateralBar/>
                <div className={styles.BodyContainer}>
                    <TopBar/>
                    {props.children}
                </div>
            </main>
        </>
    )
}